# Generated by Django 4.0.4 on 2022-05-25 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_menu_name', models.CharField(blank=True, max_length=40, verbose_name='Имя категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('cat_menu_name_image', models.ImageField(blank=True, null=True, upload_to='image/menu/%Y/%m/%d/', verbose_name='Фото категории меню')),
            ],
            options={
                'verbose_name': 'Основные блюды->Категория',
                'verbose_name_plural': 'Основные блюды->Категории',
                'ordering': ['cat_menu_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField(blank=True, verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Сообщения от пользователя',
                'verbose_name_plural': 'Сообщении от пользователей',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, upload_to='product_image/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cat_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Названия категории продукта')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Меню->Категория',
                'verbose_name_plural': 'Меню->Категории',
                'ordering': ['product_cat_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('products', models.ManyToManyField(to='Nomad_Coffee_Naryn_app.menu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователей',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='Nomad_Coffee_Naryn_app.menu_category'),
        ),
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(blank=True, max_length=40, verbose_name='Заголовок меню')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('text_menu', models.TextField(blank=True, verbose_name='Текст меню')),
                ('image_menu', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomad_Coffee_Naryn_app.catmenu', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Основная блюда',
                'verbose_name_plural': 'Основные блюды',
                'ordering': ['title_menu'],
            },
        ),
        migrations.AlterIndexTogether(
            name='menu',
            index_together={('id', 'slug')},
        ),
    ]
