# Generated by Django 4.0.4 on 2022-05-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomad_Coffee_Naryn_app', '0004_news_coffee_text_alter_news_coffee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_coffee',
            name='news_image',
            field=models.ImageField(blank=True, upload_to='image/news_image/%Y/%m/%d/', verbose_name='фото заголовоки'),
        ),
    ]
